### ISSUE TITLE
Plugin roadmap

### ISSUE THREAD

**Issue by Delounea** [Delounea/HDT-Tournament#1]
## Plugin behaviour 
 - [ ] Collect results of match
 - [ ] Handle check-in
 - [ ] Auto add next opponent to friend list
 - [ ] Screenshot of match result
 - [ ] Tournaments stats

## Supported tournament websites
 - [ ] Toornament (#)
 - [ ] Challonge (#)
